site_name: Defensoria SP
theme:
  language: pt
  palette:
    primary: red
    accent: green
  logo: assets/planejamento/logos/defensoria-logo.jpg
  favicon: images/favicon.jpg
  name: material
  features:
    - navigation.tabs
extra_css:
  - stylesheets/styles.css

dev_addr: "0.0.0.0:8000"
nav:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Processo de Design: processo-de-design.md
  - Análise de Requisitos:
    - análise-de-requisitos/1.analise-de-tarefas.md
    - análise-de-requisitos/2.guia-de-estilos.md
    - análise-de-requisitos/3.metas-de-usabilidade.md
    - análise-de-requisitos/4.perfil-de-usuarios.md
    - análise-de-requisitos/5.personas.md
    - análise-de-requisitos/6.principios-diretrizes.md
  - Design, Avaliação e Desenvolvimento:
    - Nível 1:
      - Análise de Tarefas:
        - design,avaliação-e-desenvolvimento/Nível-1/1.planejamento-avaliacao-analise-de-tarefas.md
        - design,avaliação-e-desenvolvimento/Nível-1/2.validacao-analise-tarefas.md
        - design,avaliação-e-desenvolvimento/Nível-1/3.analise-de-tarefas-v2.md
      - StoryBoard:
        - design,avaliação-e-desenvolvimento/Nível-1/4.storyboard.md
        - design,avaliação-e-desenvolvimento/Nível-1/5.planejamento-avaliacao-storyboard.md
        - design,avaliação-e-desenvolvimento/Nível-1/6.termo-consentimento-storyboard.md
        - design,avaliação-e-desenvolvimento/Nível-1/7.resultado-avaliacao-storyboard.md
    - Nível 2:
      - design,avaliação-e-desenvolvimento/Nível-2/1.prototipo-de-papel.md
      - design,avaliação-e-desenvolvimento/Nível-2/2.planejamento-da-avaliacao-prototipo-de-papel.md
      - design,avaliação-e-desenvolvimento/Nível-2/3.avaliacao-do-prototipo-de-papel.md
    - Nível 3:
      - design,avaliação-e-desenvolvimento/Nível-3/1.planejamento-avaliacao-alta-fidelidade.md
      - design,avaliação-e-desenvolvimento/Nível-3/2.termo-consentimento-alta-fidelidade.md
